[package]
name = "simp_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
cfg-if = "1.0.0"
pest = "2.7.12"
pest_derive = "2.7.12"
rustyline = "14.0.0"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = [
    "llvm14-0",
] }
